---
#task to create ssh
- name: set ssh config on customer cluster
  hosts: all
  tasks:
    - name: Set inventory ansible_port to default
      set_fact:
        ansible_port: "22"
      when: default_ssh is defined and
            default_ssh.state == "started"
      register: ssh_port_set

    - name: Setup alternate SSH port
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port 2222"

    - name: Setup SSH port
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        line: "Port 22"

    - name: Setup selinux for alternate SSH port
      seport:
        ports: "2222"
        proto: "tcp"
        setype: "ssh_port_t"
        state: "present"

    - name: Restart sshd
      service:
        name: sshd
        state: restarted
