apiVersion: v1
kind: Service
metadata:
  name: jiralert-service
spec:
  selector: # exposes any pods with the following labels as a service
    app: jiralert
  type: ClusterIP
  ports:
    - port: 9097 # this Service's port (cluster-internal IP clusterIP)
      targetPort: 9097 # pods expose this port
      # Kubernetes master will allocate a port from a flag-configured range (default: 30000-32767),
      #       #       # or we can set a specific port number (in our case).
      #             #             # Each node will proxy 32514 port (the same port number on every node) into this service.
      #                   #                   # Note that this Service will be visible as both NodeIP:nodePort and clusterIp:port
      #                   #      nodePort: 32200
      #
